### ISSUE TITLE
push 관련 오류

### ISSUE THREAD

**Issue by brightness-k** [17-1-SKKU-OSS/rocksdb#11]
![image](https://user-images.githubusercontent.com/25175915/26859343-f92df722-4b71-11e7-93c0-d79ca877edd9.png)

계속 권한이 없다고 뜨는데
git이랑 통신문제인가 해서 github에서 직접 시도해도 안되네요

**Comment by hye0nwoo** [comment]
깜빡하고 Collaborators에 추가하지 않아서 일어난 오류였습니다.
2017/06/07 11:15 경 해결 및 푸쉬 확인되었습니다.
