### ISSUE TITLE
번역 문서 static page 게시

### ISSUE THREAD

**Issue by brightness-k** [17-1-SKKU-OSS/rocksdb#13]
번역한 문서를 그냥 폴더에 넣어두기보다
정적페이지에 게시해 두는게 다른 사용자의 접근성 면에서 더 좋을 것 같습니다.
어떻게 생각하시나요?

**Comment by hye0nwoo** [comment]
재명씨가 번역한 부분이 환경셋팅 및 설치 부분이니까
"rocksDB 입문" 이나 "rocksDB 설치방법" 등의 제목으로 게시하면 좋을 것 같습니다.

**Comment by brightness-k** [comment]
추가 완료했습니다
